name: Changelog Builder Action
description: GitHub Action that builds a changelog by comparing two refs.

inputs:
  token:
    description: Your GitHub Token
    required: false
    default: ${{ github.token }}

  base-ref:
    description: The base reference name
    required: false
    default:

  head-ref:
    description: The head reference name
    required: false
    default:

  exclude-types:
    description: A comma-delimited string of types to exclude
    required: false
    default: docs,style,build

  only-types:
    description: A comma-delimited string of types to include
    required: false
    default:

  exclude-scopes:
    description: A newline-delimited string of scopes to exclude
    required: false
    default:

  show-icons:
    description: Whether icons should be shown in the resulting changelog
    required: false
    default: true

  mention-authors:
    description: Whether authors should be mentioned in the resulting changelog
    required: false
    default: true

outputs:
  changelog:
    description: The resulting changelog

  compare-url:
    description: The URL of the compare page

runs:
  using: node20
  main: dist/index.js

branding:
  icon: file-text
  color: blue
