name: Changelog Builder Action
description: GitHub Action that builds a changelog by comparing two refs.

inputs:
  token:
    description: Your GitHub Token
    required: false
    default: ${{ github.token }}

  base-ref:
    description: The base reference name
    required: false
    default:

  head-ref:
    description: The head reference name
    required: false
    default:

outputs:
  changelog:
    description: The resulting changelog

runs:
  using: node20
  main: dist/index.js

branding:
  icon: file-text
  color: blue
