name: Release
run-name: Release ${{ github.ref_name }}

on:
  push:
    tags: "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build changelog
        id: changelog
        uses: ./
        with:
          head-ref: ${{ github.ref_name }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          body: |
            ${{ steps.changelog.outputs.compare-url }}

            ${{ steps.changelog.outputs.changelog }}

      - name: Create Tag Aliases
        env:
          tag_name: ${{ github.ref_name }}
        run: |
          create_tag_alias() {
            git tag -f "$1" "$tag_name"
            git push -f origin "$1"
          }

          create_tag_alias latest
          create_tag_alias "$(printf "$tag_name" | grep -o "^[^.]*")"
